---
deployment:
  tasks:
    - export DEPLOYPATH=/home/s28sheoe5xht/public_html
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp cards.js $DEPLOYPATH
    - /bin/cp script.js $DEPLOYPATH
    - /bin/cp -R img $DEPLOYPATH
    - /bin/cp -R css $DEPLOYPATH
